"use client";
import { Roboto } from "next/font/google";
import "./globals.css";

import { ContextProvider } from "./context";
import { Metadata } from "next";

const roboto = Roboto({
  subsets: ["latin-ext"],
});
const metadata: Metadata = {
  title: "Đây là Project Nextjs",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <div className="w-full h-10 bg-amber-200 px-10 flex justify-center items-center">
          <div className="flex justify-between w-full max-w-screen-lg">
            <div>Home</div>
            <div>Login</div>
            <div>Register</div>
          </div>
        </div>
        <ContextProvider>{children}</ContextProvider>
        <div className="w-full h-10 bg-amber-200">Footer</div>
      </body>
    </html>
  );
}
